import jsPDF from 'jspdf';
import type { TestResult, AccessibilityIssue } from '../../types';
import logoImage from '../../assets/logo.png';

export async function exportToPDF(results: TestResult) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yOffset = 0;

  // Brand colors from the hero section
  const brandColor = [15, 174, 150]; // #0fae96
  const lightBrandColor = [224, 245, 241]; // #e0f5f1
  const darkGray = [55, 65, 81]; // #374151
  const lightGray = [156, 163, 175]; // #9CA3AF

  // Helper function to add header to each page
  const addHeader = () => {
    const headerHeight = 50;
    
    // Main header background with subtle gradient effect
    pdf.setFillColor(255, 255, 255); // White background
    pdf.rect(0, 0, pageWidth, headerHeight, 'F');
    
    // Top accent bar
    pdf.setFillColor(brandColor[0], brandColor[1], brandColor[2]);
    pdf.rect(0, 0, pageWidth, 3, 'F');
    
    // Light background panel for logo area
    pdf.setFillColor(lightBrandColor[0], lightBrandColor[1], lightBrandColor[2]);
    pdf.roundedRect(15, 8, pageWidth - 30, 32, 2, 2, 'F');
    
    // Add subtle shadow effect with dark border
    pdf.setDrawColor(200, 200, 200);
    pdf.setLineWidth(0.2);
    pdf.roundedRect(15, 8, pageWidth - 30, 32, 2, 2, 'S');
    
    // Add logo image with better positioning
    const logoWidth = 45;
    const logoHeight = 11.15; // Maintaining aspect ratio
    pdf.addImage(logoImage, 'PNG', 25, 12, logoWidth, logoHeight);
    
    // Vertical separator line
    pdf.setDrawColor(brandColor[0], brandColor[1], brandColor[2]);
    pdf.setLineWidth(1);
    pdf.line(85, 12, 85, 35);
    
    // Report title with improved typography
    pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text('ACCESSIBILITY REPORT', 95, 20);
    
    // Subtitle
    pdf.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text('WCAG 2.2 Compliance Analysis', 95, 28);
    
    // Date with better styling
    pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    const dateText = `Generated: ${new Date(results.timestamp).toLocaleDateString()}`;
    const dateWidth = pdf.getTextWidth(dateText);
    pdf.text(dateText, pageWidth - dateWidth - 25, 18);
    
    // Time
    pdf.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
    pdf.setFontSize(8);
    const timeText = new Date(results.timestamp).toLocaleTimeString();
    const timeWidth = pdf.getTextWidth(timeText);
    pdf.text(timeText, pageWidth - timeWidth - 25, 25);
    
    // Bottom border for header
    pdf.setDrawColor(230, 230, 230);
    pdf.setLineWidth(0.5);
    pdf.line(0, headerHeight, pageWidth, headerHeight);
    
    yOffset = headerHeight + 10;
  };

  // Helper function to add footer
  const addFooter = () => {
    pdf.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
    pdf.setFontSize(8);
    pdf.text('Generated by Heaventree - Web Accessibility Compliance Platform', 20, pageHeight - 10);
    pdf.text(`Page ${pdf.getNumberOfPages()}`, pageWidth - 30, pageHeight - 10);
  };

  // Add first page header
  addHeader();

  // Website URL and summary section
  pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text('Website Analysis', 20, yOffset);
  
  yOffset += 12;
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.text('Tested URL:', 20, yOffset);
  
  yOffset += 6;
  pdf.setTextColor(brandColor[0], brandColor[1], brandColor[2]);
  pdf.setFontSize(10);
  const urlLines = pdf.splitTextToSize(results.url, pageWidth - 40);
  pdf.text(urlLines, 20, yOffset);
  yOffset += (urlLines.length * 5) + 8;

  // Compliance summary cards
  pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text('Compliance Overview', 20, yOffset);
  
  yOffset += 15;
  
  // Summary cards in a grid layout
  const cardWidth = 40;
  const cardHeight = 25;
  const cardSpacing = 5;
  
  const summaryData = [
    { label: 'Critical', value: results.summary.critical, color: [220, 38, 127] }, // Red
    { label: 'Serious', value: results.summary.serious, color: [251, 146, 60] }, // Orange  
    { label: 'Moderate', value: results.summary.moderate, color: [250, 204, 21] }, // Yellow
    { label: 'Minor', value: results.summary.minor, color: [59, 130, 246] }, // Blue
    { label: 'Passed', value: results.summary.passes, color: brandColor }, // Green
    { label: 'Warnings', value: results.summary.warnings, color: [107, 114, 128] } // Gray
  ];

  let cardX = 20;
  let cardY = yOffset;
  
  summaryData.forEach((item, index) => {
    if (index === 3) { // Move to second row after 3 cards
      cardX = 20;
      cardY += cardHeight + cardSpacing;
    }
    
    // Card background
    pdf.setFillColor(item.color[0], item.color[1], item.color[2]);
    pdf.roundedRect(cardX, cardY, cardWidth, cardHeight, 2, 2, 'F');
    
    // Card text
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text(item.value.toString(), cardX + cardWidth/2, cardY + 12, { align: 'center' });
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.text(item.label, cardX + cardWidth/2, cardY + 20, { align: 'center' });
    
    cardX += cardWidth + cardSpacing;
  });
  
  yOffset = cardY + cardHeight + 20;

  // Add issues section
  if (results.issues.length > 0) {
    // Check if we need a new page
    if (yOffset > 200) {
      pdf.addPage();
      addHeader();
    }
    
    pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text('Issues Detected', 20, yOffset);
    
    yOffset += 12;
    
    results.issues.forEach((issue: AccessibilityIssue, index: number) => {
      // Check if we need a new page
      if (yOffset > 250) {
        pdf.addPage();
        addHeader();
      }

      // Issue number and impact badge
      const impactColors: { [key: string]: number[] } = {
        critical: [220, 38, 127],
        serious: [251, 146, 60],
        moderate: [250, 204, 21],
        minor: [59, 130, 246]
      };
      
      const impactColor = impactColors[issue.impact] || [107, 114, 128];
      
      // Impact badge
      pdf.setFillColor(impactColor[0], impactColor[1], impactColor[2]);
      pdf.roundedRect(20, yOffset, 15, 6, 1, 1, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.text(issue.impact.toUpperCase(), 27.5, yOffset + 4, { align: 'center' });
      
      // Issue number
      pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(`${index + 1}.`, 40, yOffset + 4);
      
      yOffset += 10;
      
      // Issue description
      pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      const description = pdf.splitTextToSize(issue.description, pageWidth - 50);
      pdf.text(description, 25, yOffset);
      yOffset += (description.length * 5) + 5;
      
      // WCAG Criteria
      if (issue.wcagCriteria?.length) {
        pdf.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
        pdf.setFontSize(9);
        pdf.text(`WCAG: ${issue.wcagCriteria.join(', ')}`, 25, yOffset);
        yOffset += 6;
      }

      // Affected elements (limited to first 3 for space)
      if (issue.nodes.length) {
        pdf.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
        pdf.setFontSize(8);
        pdf.text(`Affected elements: ${Math.min(issue.nodes.length, 3)} ${issue.nodes.length > 3 ? '(showing first 3)' : ''}`, 25, yOffset);
        yOffset += 5;
        
        issue.nodes.slice(0, 3).forEach((node: string) => {
          const nodeText = pdf.splitTextToSize(`• ${node}`, pageWidth - 60);
          pdf.text(nodeText, 30, yOffset);
          yOffset += (nodeText.length * 4) + 2;
        });
      }

      yOffset += 8;
    });
  }

  // Add footer to all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter();
  }

  // Add recommendations section if there are issues
  if (results.issues.length > 0) {
    pdf.addPage();
    addHeader();
    
    pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text('Recommendations', 20, yOffset);
    
    yOffset += 12;
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    
    const recommendations = [
      '• Prioritize fixing critical and serious issues first',
      '• Review WCAG 2.2 guidelines for detailed implementation guidance',
      '• Test with actual assistive technology users when possible',
      '• Implement automated accessibility testing in your development workflow',
      '• Schedule regular accessibility audits to maintain compliance'
    ];
    
    recommendations.forEach(rec => {
      const recLines = pdf.splitTextToSize(rec, pageWidth - 40);
      pdf.text(recLines, 25, yOffset);
      yOffset += (recLines.length * 6) + 4;
    });
    
    // Add contact information
    yOffset += 15;
    pdf.setFillColor(lightBrandColor[0], lightBrandColor[1], lightBrandColor[2]);
    pdf.roundedRect(20, yOffset, pageWidth - 40, 25, 3, 3, 'F');
    
    yOffset += 8;
    pdf.setTextColor(brandColor[0], brandColor[1], brandColor[2]);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text('Need Help?', 25, yOffset);
    
    yOffset += 8;
    pdf.setTextColor(darkGray[0], darkGray[1], darkGray[2]);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text('Visit our help center or contact our accessibility experts for guidance', 25, yOffset);
    
    yOffset += 6;
    pdf.setTextColor(brandColor[0], brandColor[1], brandColor[2]);
    pdf.text('https://heaventree.com/help', 25, yOffset);
    
    addFooter();
  }

  // Generate filename from URL
  const urlForFilename = results.url
    .replace(/^https?:\/\//, '')
    .replace(/[^a-zA-Z0-9]/g, '-')
    .slice(0, 50);
  
  const dateString = new Date().toISOString().split('T')[0];
  
  // Save the PDF
  pdf.save(`Heaventree-Report-${urlForFilename}-${dateString}.pdf`);
}